# Exercise 1.01: Matrix Operations Using NumPy

We will be using Jupyter Notebook and the following matrix to solve this exercise.

We will calculate the square of the matrix, which is determinant of the matrix and the transpose of the matrix shown in the following figure, using NumPy:

![Figure 1.2](img/fig1_02.jpg)

1.- Import the `numpy` library as `np`

In [ ]:
import numpy as np

2.- Create a two-dimensional array called `A` for storing the $[[1,2,3],[4,5,6],[7,8,9]]$ matrix using `np.mat`, then show de variable A

Output:

```
matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
```

  > If you have created an np.array instead of np.mat, the solution for the array multiplication will be incorrect.

In [ ]:
A = np.mat([[1,2,3],[4,5,6],[7,8,9]])
A

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

3.- Perform matrix multiplication using the asterisk and save the result in a variable called `matmult`

In [ ]:
mtzMult = A * A
mtzMult

matrix([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

4.- Manually calculate the square of A by performing matrix multiplication. Show the result.

Output:

```
30
```

In [ ]:
1*1+2*4+3*7

30

5.- Use `np.linalg.det` to calculate the determinant of the matrix and save the result in a variable called `det`.

Output:

```
0.0
```

In [ ]:
det = np.linalg.det(A)
det

0.0

6.- Use `np.matrix.transpose` to get the transpose of the matrix and save the result in a variable called `transpose`

Output:

```
matrix([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])
```

In [ ]:
transpose = np.matrix.transpose(A)
transpose

matrix([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

By completing this exercise, you have seen that NumPy comes with many useful features for vectors, matrices, and other mathematical structures.

In the upcoming section, we will be implementing AI in an interesting tic-tac-toe game using Python.